### ISSUE TITLE
decouple.UndefinedValueError

### ISSUE THREAD

**Issue by lekhanaby** [shivamsaraswat/credit-card-fraud-detection#1]
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\credit-card-fraud-detection-main\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\hp\Downloads\credit-card-fraud-detection-main\djecommerce\settings\production.py", line 1, in <module>
    from .base import *
  File "C:\Users\hp\Downloads\credit-card-fraud-detection-main\djecommerce\settings\base.py", line 7, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

whenever i try to run the program i get this error

**Comment by shivamsaraswat** [comment]
You have to put SECRET_KEY from the Stripe platform in Django files.
